version: "3.9"
services:
  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sieve
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  minio:
    image: minio/minio:RELEASE.2024-09-07T15-59-28Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - miniodata:/data

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    env_file: ./opensearch.env
    ports: ["9200:9200", "9600:9600"]

  redpanda:
    image: redpandadata/redpanda:v24.1.10
    command:
      - redpanda start --overprovisioned --smp 1 --memory 512M --reserve-memory 0M --check=false
    ports: ["9092:9092", "9644:9644"]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    env_file: ./mlflow.env
    ports: ["5001:5000"]
    depends_on:
      - pg

volumes:
  pgdata: {}
  miniodata: {}
